#! /bin/sh
set -eu
NAME="${0##*/}"

main() {
  if [ "$#" -lt 1 ]; then
    usage
    exit 2
  fi
  case "$1" in
    -h|--help)
      usage
      exit 0
      ;;
    -g|--get)
      get_transparency
      exit 0
      ;;
    -s|--set)
      if [ "$#" -lt 2 ]; then
        echo "$NAME: no specify percentage"
        exit 2
      fi
      set_transparency "$2"
      exit 0
      ;;
    *)
      echo "$NAME: invalid operation '$1'"
      exit 2
      ;;
  esac
}
usage() {
  echo "usage: $NAME <operation> [...]"
  echo "operations:"
  echo "  $NAME {-h --help}              # show this help message"
  echo "  $NAME {-g --get}               # show the current transparency"
  echo "  $NAME {-s --set} <percentage>  # set the transparency"
}
schema() {
  (
    uuid="$(gsettings get org.gnome.Terminal.ProfilesList default)"
    uuid="${uuid##\'}"
    uuid="${uuid%%\'}"
    schema="org.gnome.Terminal.Legacy.Profile:"
    echo "$schema/org/gnome/terminal/legacy/profiles:/:$uuid/"
  )
}
get_transparency() {
  (
    schema="$(schema)"
    gsettings get "$schema" "background-transparency-percent"
  )
}
set_transparency() {
  (
    schema=$(schema)
    per="$1"
    if [ "$per" -eq 0 ]; then
      gsettings set "$schema" "use-transparent-background" "false"
    else
      gsettings set "$schema" "use-transparent-background" "true"
    fi
    gsettings set "$schema" "background-transparency-percent" "$per"
  )
}

main $*
exit 0
