#!/bin/sh
set -eu

usage() {
  cat <<__USAGE__ >&2
usage: ${0##*/} <operation> [...]
modify transparency of gnome-terminal.

operations:
  ${0##*/} {-h --help}              # show this help message
  ${0##*/} {-g --get}               # show the current transparency
  ${0##*/} {-s --set} <percentage>  # set the transparency
__USAGE__
}

warn() {
  echo "${0##*/}: $*" >&2
}

schema() {
  (
    uuid="$(gsettings get org.gnome.Terminal.ProfilesList default)"
    uuid="${uuid##\'}"
    uuid="${uuid%%\'}"
    schema="org.gnome.Terminal.Legacy.Profile:"
    echo "$schema/org/gnome/terminal/legacy/profiles:/:$uuid/"
  )
}

get_transparency() {
  (
    schema="$(schema)"
    gsettings get "$schema" "background-transparency-percent"
  )
}

set_transparency() {
  (
    schema="$(schema)"
    per="$1"
    if [ "$per" -eq 0 ]; then
      gsettings set "$schema" "use-transparent-background" "false"
    else
      gsettings set "$schema" "use-transparent-background" "true"
    fi
    gsettings set "$schema" "background-transparency-percent" "$per"
  )
}

if [ $# -lt 1 ]; then
  usage
  exit 2
fi
case "$1" in
  -h|-help|--help)
    usage
    exit 0
    ;;
  -g|-get|--get)
    get_transparency
    exit 0
    ;;
  -s|-set|--set)
    if [ $# -lt 2 ]; then
      warn "no specify percentage"
      exit 2
    fi
    set_transparency "$2"
    exit 0
    ;;
  *)
    warn "invalid operation '$1'"
    exit 2
    ;;
esac
